RGBLIGHT_ENABLE = no        # Enable WS2812 RGB underlight.
AUTO_SHIFT_ENABLE = yes
VPATH  +=  keyboards/gboards/
COMBO_ENABLE=yes
LEADER_ENABLE = yes
TAP_DANCE_ENABLE = no

POINTING_DEVICE_ENABLE = yes
POINTING_DEVICE_DRIVER = pmw3360


LTO_ENABLE = yes
CONSOLE_ENABLE = no
COMMAND_ENABLE = no
MOUSEKEY_ENABLE = yes
EXTRAKEY_ENABLE = yes

SPACE_CADET_ENABLE = no
GRAVE_ESC_ENABLE = no
MAGIC_ENABLE = no
MUSIC_ENABLE = no
