MOUSEKEY_ENABLE = no
EXTRAKEY_ENABLE = yes
CONSOLE_ENABLE = no
RGBLIGHT_ENABLE = yes
ENCODER_ENABLE = yes
LTO_ENABLE = yes
OLED_ENABLE = yes
OLED_DRIVER = SSD1306
#RGB_MATRIX_ENABLE = yes
#RGB_MATRIX_DRIVER = WS2812
EXTRAFLAGS += -flto  # from Drashna to free up memory in the AVR


WPM_ENABLE = no
AUTO_SHIFT_ENABLE = yes

LTO_ENABLE = yes
CONSOLE_ENABLE = no
COMMAND_ENABLE = no
MOUSEKEY_ENABLE = no

